window.MILK_TEA_DATA = {
  meta: {
    productName: "我的奶茶版图",
    gravityNote: "若发现某省变胖，请不要惊慌，那可能是奶茶品牌密度过高，引发了局部空间膨胀。"
  },
  provinces: [
    {
        "id": "xinjiang",
        "name": "新疆",
        "x": 38,
        "y": 116,
        "w": 190,
        "h": 126,
        "color": "#b9d3a9",
        "line": "geo"
    },
    {
        "id": "inner-mongolia",
        "name": "内蒙古",
        "x": 322,
        "y": 120,
        "w": 228,
        "h": 92,
        "color": "#b7d4bb",
        "line": "geo"
    },
    {
        "id": "heilongjiang",
        "name": "黑龙江",
        "x": 592,
        "y": 80,
        "w": 108,
        "h": 92,
        "color": "#f1d8a4",
        "line": "geo"
    },
    {
        "id": "gansu",
        "name": "甘肃",
        "x": 236,
        "y": 226,
        "w": 126,
        "h": 82,
        "color": "#f1cf88",
        "line": "geo"
    },
    {
        "id": "jilin",
        "name": "吉林",
        "x": 606,
        "y": 170,
        "w": 82,
        "h": 58,
        "color": "#f0d39b",
        "line": "geo"
    },
    {
        "id": "qinghai",
        "name": "青海",
        "x": 178,
        "y": 286,
        "w": 144,
        "h": 92,
        "color": "#ead7a8",
        "line": "geo"
    },
    {
        "id": "ningxia",
        "name": "宁夏",
        "x": 350,
        "y": 304,
        "w": 58,
        "h": 46,
        "color": "#ead7a8",
        "line": "geo"
    },
    {
        "id": "liaoning",
        "name": "辽宁",
        "x": 588,
        "y": 236,
        "w": 86,
        "h": 54,
        "color": "#bdd6be",
        "line": "geo"
    },
    {
        "id": "tibet",
        "name": "西藏",
        "x": 48,
        "y": 334,
        "w": 166,
        "h": 110,
        "color": "#d1c2ad",
        "line": "geo"
    },
    {
        "id": "shanxi",
        "name": "山西",
        "x": 450,
        "y": 316,
        "w": 66,
        "h": 88,
        "color": "#e4c593",
        "line": "geo"
    },
    {
        "id": "beijing",
        "name": "北京",
        "x": 538,
        "y": 254,
        "w": 48,
        "h": 36,
        "color": "#f2d99b",
        "line": "geo"
    },
    {
        "id": "tianjin",
        "name": "天津",
        "x": 572,
        "y": 302,
        "w": 48,
        "h": 36,
        "color": "#f2d99b",
        "line": "geo"
    },
    {
        "id": "hebei",
        "name": "河北",
        "x": 504,
        "y": 282,
        "w": 78,
        "h": 82,
        "color": "#c5d8bd",
        "line": "geo"
    },
    {
        "id": "shandong",
        "name": "山东",
        "x": 574,
        "y": 376,
        "w": 106,
        "h": 72,
        "color": "#bcd5bf",
        "line": "geo"
    },
    {
        "id": "shaanxi",
        "name": "陕西",
        "x": 378,
        "y": 352,
        "w": 74,
        "h": 104,
        "color": "#c7d99b",
        "line": "geo"
    },
    {
        "id": "henan",
        "name": "河南",
        "x": 474,
        "y": 398,
        "w": 96,
        "h": 72,
        "color": "#f2d09b",
        "line": "geo"
    },
    {
        "id": "sichuan",
        "name": "四川",
        "x": 238,
        "y": 462,
        "w": 164,
        "h": 116,
        "color": "#f0c58f",
        "line": "geo"
    },
    {
        "id": "chongqing",
        "name": "重庆",
        "x": 398,
        "y": 486,
        "w": 66,
        "h": 48,
        "color": "#efd69a",
        "line": "geo"
    },
    {
        "id": "hubei",
        "name": "湖北",
        "x": 446,
        "y": 488,
        "w": 112,
        "h": 74,
        "color": "#b8cfaa",
        "line": "geo"
    },
    {
        "id": "anhui",
        "name": "安徽",
        "x": 560,
        "y": 480,
        "w": 80,
        "h": 70,
        "color": "#ead2a1",
        "line": "geo"
    },
    {
        "id": "jiangsu",
        "name": "江苏",
        "x": 634,
        "y": 454,
        "w": 72,
        "h": 88,
        "color": "#bfd9c1",
        "line": "geo"
    },
    {
        "id": "guizhou",
        "name": "贵州",
        "x": 362,
        "y": 590,
        "w": 88,
        "h": 70,
        "color": "#c8d9a0",
        "line": "geo"
    },
    {
        "id": "hunan",
        "name": "湖南",
        "x": 468,
        "y": 574,
        "w": 90,
        "h": 88,
        "color": "#f2d092",
        "line": "geo"
    },
    {
        "id": "shanghai",
        "name": "上海",
        "x": 682,
        "y": 536,
        "w": 38,
        "h": 34,
        "color": "#f0c17f",
        "line": "geo"
    },
    {
        "id": "yunnan",
        "name": "云南",
        "x": 256,
        "y": 646,
        "w": 108,
        "h": 104,
        "color": "#ead1a2",
        "line": "geo"
    },
    {
        "id": "guangxi",
        "name": "广西",
        "x": 382,
        "y": 690,
        "w": 96,
        "h": 82,
        "color": "#efcf8c",
        "line": "geo"
    },
    {
        "id": "jiangxi",
        "name": "江西",
        "x": 562,
        "y": 588,
        "w": 82,
        "h": 88,
        "color": "#e7c793",
        "line": "geo"
    },
    {
        "id": "zhejiang",
        "name": "浙江",
        "x": 642,
        "y": 572,
        "w": 72,
        "h": 80,
        "color": "#b8d6bc",
        "line": "geo"
    },
    {
        "id": "fujian",
        "name": "福建",
        "x": 624,
        "y": 670,
        "w": 76,
        "h": 82,
        "color": "#e8d29b",
        "line": "geo"
    },
    {
        "id": "guangdong",
        "name": "广东",
        "x": 486,
        "y": 690,
        "w": 136,
        "h": 78,
        "color": "#b9d9bd",
        "line": "geo"
    },
    {
        "id": "hongkong",
        "name": "香港",
        "x": 610,
        "y": 764,
        "w": 42,
        "h": 28,
        "color": "#f7e7c8",
        "line": "geo"
    },
    {
        "id": "macau",
        "name": "澳门",
        "x": 560,
        "y": 766,
        "w": 42,
        "h": 28,
        "color": "#f7e7c8",
        "line": "geo"
    },
    {
        "id": "hainan",
        "name": "海南",
        "x": 484,
        "y": 804,
        "w": 58,
        "h": 38,
        "color": "#c7e2c8",
        "line": "geo"
    },
    {
        "id": "taiwan",
        "name": "台湾",
        "x": 648,
        "y": 664,
        "w": 72,
        "h": 112,
        "color": "#b9d6c3",
        "line": "geo"
    }
],
  brands: [
    { id: "mixue", name: "蜜雪冰城", provinceId: "henan", city: "郑州", confidence: "A", tags: ["平价", "国民", "冰淇淋", "柠檬水", "下沉"], noteType: "本命 BGM", note: "你爱我，我爱你，蜜雪冰城甜蜜蜜。" },
    { id: "heytea", name: "喜茶", provinceId: "guangdong", city: "江门", confidence: "A", tags: ["芝士茶", "鲜果", "创新", "网红", "茶感"], noteType: "本命气质", note: "你偏爱带一点开创感的茶饮，最好连第一口都像新品发布。" },
    { id: "nayuki", name: "奈雪的茶", provinceId: "guangdong", city: "深圳", confidence: "B", tags: ["鲜果", "软欧包", "都市", "精致", "中高价"], noteType: "本命气质", note: "你需要的不止一杯饮料，还有一个体面的下午出口。" },
    { id: "mollytea", name: "茉莉奶白", provinceId: "guangdong", city: "深圳", confidence: "B", tags: ["花香", "茉莉", "新中式", "精致", "奶香"], noteType: "本命气质", note: "你对花香很敏感，清雅要有，奶香也不能掉线。" },
    { id: "linlee", name: "LINLEE 林里", provinceId: "guangdong", city: "湛江", confidence: "A", tags: ["手打柠檬茶", "潮流", "解腻", "轻负担", "柠檬"], noteType: "偏好注脚", note: "你的快乐需要一点酸，一点冰，和一口把困意摇醒的柠檬茶。" },
    { id: "qiudashu", name: "丘大叔", provinceId: "guangdong", city: "广州", confidence: "C", tags: ["鸭屎香", "柠檬茶", "广府", "清爽", "茶感"], noteType: "偏好注脚", note: "你对茶底有要求，柠檬只是负责把它推到台前。" },
    { id: "gaga", name: "gaga 鲜语", provinceId: "guangdong", city: "深圳", confidence: "B", tags: ["鲜果", "轻食", "生活方式", "都市", "精致"], noteType: "本命气质", note: "你喝的是鲜果，也是城市生活里一点松弛的秩序感。" },
    { id: "chapanda", name: "茶百道", provinceId: "sichuan", city: "成都", confidence: "A", tags: ["鲜果", "杨枝甘露", "大众", "稳定", "中价"], noteType: "偏好注脚", note: "你相信稳定发挥，杯杯都不用赌运气。" },
    { id: "shuyi", name: "书亦烧仙草", provinceId: "sichuan", city: "成都", confidence: "A", tags: ["烧仙草", "小料", "饱腹", "大众", "甜品"], noteType: "偏好注脚", note: "你对奶茶的要求很朴素：好喝，最好还能嚼。" },
    { id: "yizhisuanniunai", name: "一只酸奶牛", provinceId: "chongqing", city: "重庆", confidence: "A", type: "local", tags: ["酸奶", "紫米", "重庆", "饮品", "地方款"], noteType: "隐藏支线", note: "你知道重庆不只有火锅，酸奶和紫米也能在地图上拥有姓名。" },
    { id: "chagee", name: "霸王茶姬", provinceId: "yunnan", city: "昆明", confidence: "A", tags: ["原叶茶", "东方茶", "控糖", "新中式", "茶感"], noteType: "本命气质", note: "茶感要清楚，奶香要克制，东方感要拉满。" },
    { id: "guming", name: "古茗", provinceId: "zhejiang", city: "温岭", confidence: "A", tags: ["鲜果", "大众", "供应链", "稳定", "小城"], noteType: "偏好注脚", note: "你喜欢日常稳定的好喝，比一次惊艳更重要。" },
    { id: "yiming", name: "一鸣真鲜奶吧", provinceId: "zhejiang", city: "温州", confidence: "B", tags: ["鲜奶", "早餐", "奶吧", "江浙日常", "奶香"], noteType: "偏好注脚", note: "你的奶茶版图里，鲜奶和早餐也有姓名。" },
    { id: "chayan", name: "茶颜悦色", provinceId: "hunan", city: "长沙", confidence: "A", tags: ["国风", "城市名片", "文创", "旅行打卡", "茶感"], noteType: "本命气质", note: "一杯茶里，有一点长沙的慢和雅。" },
    { id: "ningji", name: "柠季", provinceId: "hunan", city: "长沙", confidence: "A", tags: ["手打柠檬茶", "去油青年", "年轻", "清爽", "柠檬"], noteType: "偏好注脚", note: "你不是口渴，你是在给今天去油。" },
    { id: "yihetang", name: "益禾堂", provinceId: "hubei", city: "武汉", confidence: "A", tags: ["烤奶", "平价", "校园", "甜", "快乐"], noteType: "偏好注脚", note: "你心里一直有个校园小卖部，那里永远卖烤奶。" },
    { id: "idrink", name: "吾饮良品", provinceId: "hubei", city: "武汉", confidence: "B", tags: ["水果茶", "港式潮饮", "区域老牌", "年轻", "鲜果"], noteType: "偏好注脚", note: "你喜欢老牌子，也喜欢它偶尔带点新潮。" },
    { id: "yeye", name: "爷爷不泡茶", provinceId: "hubei", city: "武汉", confidence: "B", tags: ["武汉茶", "现代国风", "地域", "新锐", "茶感"], noteType: "本命气质", note: "你偏爱有地方脾气的新中式，不想喝得太像别人。" },
    { id: "auntea", name: "沪上阿姨", provinceId: "shanghai", city: "上海", confidence: "B", tags: ["鲜果茶", "五谷茶饮", "血糯米", "大众", "甜品"], noteType: "偏好注脚", note: "你相信五谷和水果都能进杯子，热闹一点也没关系。" },
    { id: "lelecha", name: "乐乐茶", provinceId: "shanghai", city: "上海", confidence: "B", tags: ["鲜果茶", "软欧包", "都市", "网红", "精致"], noteType: "偏好注脚", note: "你爱喝，也爱逛，最好一杯茶旁边还能配点面包香。" },
    { id: "happylemon", name: "快乐柠檬", provinceId: "shanghai", city: "上海", confidence: "B", tags: ["柠檬茶", "活力", "老牌", "海外", "清爽"], noteType: "偏好注脚", note: "你对快乐的理解很直接：酸甜冰爽，立刻生效。" },
    { id: "alittletea", name: "一点点", provinceId: "shanghai", city: "上海", confidence: "A", tags: ["台式手摇", "珍珠奶茶", "老牌", "日常", "小料"], noteType: "偏好注脚", note: "你喜欢老派手摇的日常感，少一点花活，多一点稳定。" },
    { id: "sweetseven", name: "7 分甜", provinceId: "jiangsu", city: "苏州", confidence: "A", tags: ["杨枝甘露", "芒果", "甜品杯", "鲜果", "甜品"], noteType: "偏好注脚", note: "你不是只想喝奶茶，你想喝一杯可以吸的甜品。" },
    { id: "moqi", name: "茉沏", provinceId: "jiangsu", city: "苏州", confidence: "A", tags: ["江南茶饮", "花茶", "碧螺春", "雅致", "茶感"], noteType: "本命气质", note: "你偏爱江南式清雅，甜要收着，香要慢慢来。" },
    { id: "xuncha", name: "巡茶", provinceId: "jiangsu", city: "苏州", confidence: "B", tags: ["茶饮轻烘焙", "东方茶点", "江南", "茶感", "甜品"], noteType: "偏好注脚", note: "你对茶点搭配有执念，喝茶这件事要有完整队形。" },
    { id: "fuxiaotao", name: "伏小桃", provinceId: "jiangsu", city: "南京", confidence: "C", tags: ["桃子", "创意茶饮", "年轻", "城市感", "鲜果"], noteType: "偏好注脚", note: "你会被漂亮名字和水果香一起说服。" },
    { id: "chaseyanyu", name: "茶色烟雨", provinceId: "jiangsu", city: "苏州", confidence: "B", tags: ["竹筒茶", "景区", "江南", "城市特色", "打卡"], noteType: "偏好注脚", note: "你很难拒绝一杯带着景区风声的茶。" },
    { id: "tianlala", name: "甜啦啦", provinceId: "anhui", city: "蚌埠", confidence: "A", tags: ["鲜果茶", "平价", "下沉", "大杯", "国民"], noteType: "偏好注脚", note: "你知道大杯鲜果茶的含金量，尤其是在热得不讲理的时候。" },
    { id: "kawanka", name: "卡旺卡", provinceId: "anhui", city: "合肥", confidence: "B", type: "local", tags: ["华东本土", "直营", "稳定", "温和", "奶茶"], noteType: "偏好注脚", note: "你喜欢不吵不闹的稳定本地牌。" },
    { id: "klfs", name: "快乐番薯", provinceId: "fujian", city: "厦门", confidence: "A", tags: ["番薯", "奶茶", "轻食", "平价", "闽派"], noteType: "偏好注脚", note: "你对番薯的信任，已经延伸进了奶茶杯。" },
    { id: "hujian", name: "壶见", provinceId: "fujian", city: "泉州", confidence: "B", type: "local", tags: ["闽式茶饮", "国风", "茶感", "地域", "新中式"], noteType: "本命气质", note: "你想喝一点闽南风骨，也想喝一点茶的正经。" },
    { id: "ashui", name: "阿水大杯茶", provinceId: "shandong", city: "济南", confidence: "B", type: "local", tags: ["大杯", "老牌", "平价", "区域茶饮", "国民"], noteType: "偏好注脚", note: "你对大杯有基本尊重，对老牌也有基本信任。" },
    { id: "iceage", name: "冰雪时光", provinceId: "shandong", city: "泰安", confidence: "B", tags: ["冰淇淋", "平价", "全国连锁", "快乐", "甜"], noteType: "偏好注脚", note: "你要的是冰、甜和立刻降温的朴素快乐。" },
    { id: "chahuanong", name: "茶话弄", provinceId: "shaanxi", city: "西安", confidence: "A", tags: ["长安", "新中式", "桂花乌龙", "文化", "茶感"], noteType: "本命气质", note: "你喜欢把长安的风，泡进一杯桂花乌龙里。" },
    { id: "fangha", name: "放哈", provinceId: "gansu", city: "兰州", confidence: "B", type: "local", tags: ["甜醅子", "西北", "地域", "豪爽", "鲜奶"], noteType: "偏好注脚", note: "烦事先放哈，甜醅子会替你把情绪放松一点。" },
    { id: "liumangxiansheng", name: "榴芒先生", provinceId: "heilongjiang", city: "哈尔滨", confidence: "B", type: "local", tags: ["水果捞", "鲜果茶", "东北", "芒果榴莲", "甜品"], noteType: "隐藏支线", note: "你对东北水果茶有额外好奇，最好一杯里热闹到像水果摊开会。" },
    { id: "cweinanniu", name: "C位牛男", provinceId: "jilin", city: "长春", confidence: "C", type: "local", tags: ["现煮奶茶", "水果茶", "长春", "东北", "本土"], noteType: "隐藏支线", note: "你在长春的茶饮地图上不走空手路，现煮和现做才有安全感。" },
    { id: "sevenhundredcc", name: "700CC 天然苏打水鲜果茶", provinceId: "liaoning", city: "沈阳", confidence: "A", type: "local", tags: ["天然苏打水", "鲜果茶", "东北", "区域茶饮", "清爽"], noteType: "隐藏支线", note: "你相信东北茶饮也能有气泡感，清爽这件事要有自己的水源。" },
    { id: "zuoshoubian", name: "左手边", provinceId: "shanxi", city: "晋中", confidence: "B", type: "local", tags: ["山西本土", "鲜奶", "水果茶", "健康", "地方款"], noteType: "隐藏支线", note: "你喜欢把山西本土小店收进版图，离心最近的那杯也要有姓名。" },
    { id: "xiaomanteatian", name: "小满茶田", provinceId: "beijing", city: "北京", confidence: "B", type: "local", tags: ["车厘子", "鲜果茶", "高价值水果", "直营", "都市"], noteType: "本命气质", note: "你对水果茶的预算有自己的坚持，车厘子和青提最好都要有存在感。" },
    { id: "xiashunaimo", name: "夏树奶沫", provinceId: "tianjin", city: "天津", confidence: "C", type: "local", tags: ["奶盖", "天津本土", "慢生活", "健康饮品", "奶香"], noteType: "隐藏支线", note: "你在天津的杯子里找奶盖的厚度，也找一点慢悠悠的松弛感。" },
    { id: "shijingpo", name: "市井婆豆沙牛乳", provinceId: "hebei", city: "石家庄", confidence: "B", type: "local", tags: ["豆沙牛乳", "平价", "石家庄", "小料", "奶香"], noteType: "隐藏支线", note: "你对豆沙和牛乳的组合很宽容，最好甜得朴素又扎实。" },
    { id: "suishiye", name: "随时椰", provinceId: "hainan", city: "海口", confidence: "A", type: "local", tags: ["椰茶", "海南", "椰子", "老爸茶", "海岛"], noteType: "隐藏支线", note: "你喝的是椰香，也是海口骑楼老街吹过来的一点热带风。" },
    { id: "chaballet", name: "茶芭蕾", provinceId: "xinjiang", city: "乌鲁木齐", confidence: "B", type: "local", tags: ["新疆鲜奶", "鲜果", "酸奶", "本土", "隐藏款"], noteType: "隐藏支线", note: "你对边疆鲜奶和水果香有探索欲，主线之外也要开图。" },
    { id: "mongolian-milk-tea", name: "蒙古奶茶", provinceId: "inner-mongolia", city: "呼和浩特", confidence: "B", type: "landmark", tags: ["传统乳茶", "咸奶茶", "草原", "奶香", "茶饮地标"], noteType: "茶饮地标", note: "你的奶茶版图里，也需要一碗热乎乎的草原咸奶茶。" },
    { id: "qidasu", name: "杞大叔 De 茶", provinceId: "ningxia", city: "银川", confidence: "B", type: "local", tags: ["枸杞", "宁夏", "鲜奶", "健康", "隐藏款"], noteType: "隐藏支线", note: "你愿意相信，枸杞也能从保温杯走进奶茶杯。" },
    { id: "sanjiangxue", name: "三江雪青稞奶茶", provinceId: "qinghai", city: "西宁", confidence: "C", type: "landmark", tags: ["青稞", "高原", "枸杞", "奶香", "茶饮地标"], noteType: "茶饮地标", note: "你喝的是高原风味，也是青稞和奶香的一次会师。" },
    { id: "guangming-teahouse", name: "光明港琼甜茶馆", provinceId: "tibet", city: "拉萨", confidence: "B", type: "landmark", tags: ["藏式甜茶", "甜茶馆", "地标", "市井", "奶香"], noteType: "茶饮地标", note: "你不是只收集品牌，也会给一座城市的甜茶时光留位置。" },
    { id: "quchashan", name: "去茶山", provinceId: "guizhou", city: "贵阳", confidence: "B", type: "local", tags: ["贵州风土", "山地", "地方食材", "精品茶", "地域"], noteType: "本命气质", note: "你对地方风物有好奇心，越不像标准答案越想试。" },
    { id: "ahma", name: "阿嬷手作", provinceId: "guangxi", city: "南宁", confidence: "B", type: "local", tags: ["手作", "水牛奶", "清补凉", "南方烟火气", "地域"], noteType: "本命气质", note: "你偏爱有手作温度的杯子，像从家里端出来。" },
    { id: "hongdu", name: "洪都大拇指", provinceId: "jiangxi", city: "南昌", confidence: "C", type: "local", tags: ["国风奶茶", "烤肠", "高性价比", "本土", "地域"], noteType: "偏好注脚", note: "你对本土小吃和奶茶联手这件事，毫无抵抗力。" },
    { id: "lanfongyuen", name: "兰芳园", provinceId: "hongkong", city: "香港", confidence: "B", type: "landmark", tags: ["港式奶茶", "丝袜奶茶", "老字号", "茶餐厅", "地标"], noteType: "茶饮地标", note: "你把港式奶茶也算进版图，茶餐厅的冰室风声不能缺席。" },
    { id: "saintsalp", name: "仙迹岩", provinceId: "hongkong", city: "香港", confidence: "B", type: "local", tags: ["珍珠奶茶", "港式手摇", "区域茶饮", "老牌", "奶茶"], noteType: "隐藏支线", note: "你愿意给香港手摇茶老牌留一格，不只喝路过的游客款。" },
    { id: "yuezhicha", name: "悦之茶", provinceId: "macau", city: "澳门", confidence: "B", type: "local", tags: ["澳门本土", "鲜果茶", "奶茶", "年轻", "隐藏款"], noteType: "隐藏支线", note: "你在澳门不只找蛋挞，也会顺手把本地茶饮收进图鉴。" },
    { id: "unceasingly", name: "不已手制柠檬茶", provinceId: "macau", city: "澳门", confidence: "C", type: "local", tags: ["手制柠檬茶", "澳门本土", "清爽", "小店", "隐藏款"], noteType: "隐藏支线", note: "你对小店的手作酸香有雷达，越像街角偶遇越想点。" },
    { id: "coco", name: "CoCo 都可", provinceId: "taiwan", city: "淡水", confidence: "A", tags: ["珍珠奶茶", "国民", "老牌", "活力", "小料"], noteType: "本命气质", note: "你心里有一杯经典珍奶，怎么换季都不会过时。" },
    { id: "milksha", name: "迷客夏", provinceId: "taiwan", city: "台南", confidence: "A", tags: ["鲜奶", "牧场", "天然", "奶香", "健康"], noteType: "本命气质", note: "你信任鲜奶的干净感，越简单越能喝出差别。" },
    { id: "50lan", name: "50 岚", provinceId: "taiwan", city: "台南", confidence: "B", tags: ["手摇老牌", "珍珠", "经典", "日常", "小料"], noteType: "偏好注脚", note: "你喜欢经典手摇的节奏，熟悉本身就是一种好喝。" },
    { id: "thealley", name: "鹿角巷", provinceId: "taiwan", city: "桃园中坜", confidence: "B", tags: ["黑糖", "网红", "美学", "打卡", "甜"], noteType: "偏好注脚", note: "你会被漂亮的杯子吸引，但也需要甜味真的撑住场面。" }
  ],
  personaRules: [
    { title: "平价快乐主义者", tags: ["平价", "国民", "下沉", "大杯"], line: "你要的是随手可得的甜，不是仪式感的账单。" },
    { title: "东方茶感信徒", tags: ["原叶茶", "新中式", "茶感", "东方茶", "国风"], line: "茶味必须先站出来，奶香只是帮它撑场面。" },
    { title: "鲜果解腻派", tags: ["鲜果", "柠檬", "手打柠檬茶", "清爽", "解腻"], line: "你喝的不是酸，是把一天的油腻关掉。" },
    { title: "城市打卡收藏家", tags: ["城市名片", "旅行打卡", "网红", "打卡", "文创"], line: "每喝一杯，你都像给一座城市盖了一枚章。" },
    { title: "小料饱腹型选手", tags: ["烧仙草", "小料", "甜品", "杨枝甘露", "番薯"], line: "在你这里，奶茶不是饮料，是一顿轻型下午饭。" },
    { title: "江南清雅派", tags: ["江南", "花茶", "碧螺春", "雅致"], line: "你偏爱清清爽爽的茶香，甜可以有，但不能喧宾夺主。" },
    { title: "珠三角柠檬风暴", tags: ["广东", "柠檬茶", "手打柠檬茶", "鸭屎香"], line: "你的人生需要一点酸，一点冰，和一杯用力摇醒的柠檬茶。" },
    { title: "长沙文创信徒", tags: ["长沙", "国风", "文创", "城市名片"], line: "你喝奶茶，也喝一点城市审美和排队仪式感。" },
    { title: "下沉市场快乐船长", tags: ["平价", "大杯", "下沉", "县城"], line: "你深知真正的快乐不一定贵，但一定要够大杯。" },
    { title: "都市精致下午茶人", tags: ["中高价", "软欧包", "精致", "都市"], line: "你不是在买饮料，你是在给下午安排一个体面出口。" },
    { title: "地域风味采样员", tags: ["地域", "西北", "贵州风土", "闽派", "南方烟火气"], line: "你喝奶茶像旅行，越有地方味，越想试试看。" },
    { title: "甜品杯巡游者", tags: ["杨枝甘露", "芒果", "芋圆", "甜品", "甜"], line: "你对奶茶的要求很简单：能喝，最好还能嚼。" }
  ],
  levels: [
    { min: 1, max: 5, title: "奶茶新手村插管员" },
    { min: 6, max: 12, title: "稳定复购型选手" },
    { min: 13, max: 20, title: "城市奶茶探索家" },
    { min: 21, max: 30, title: "全国茶饮巡游者" },
    { min: 31, max: 99, title: "奶茶图鉴收集狂" }
  ],
  curiosity: [
    { min: 0, max: 0, title: "稳定复购派" },
    { min: 1, max: 3, title: "谨慎尝鲜派" },
    { min: 4, max: 8, title: "奶茶好奇宝宝" },
    { min: 9, max: 99, title: "探店雷达启动者" }
  ]
};
